### ISSUE TITLE
Can't locate com.sparkpost.client-server-protocol-lib in mvnrepository

### ISSUE THREAD

**Issue by sks** [SparkPost/java-sparkpost#19]
Hi Team,

Where excatly is the dependency hosted,

```
<dependency>
    <groupId>com.sparkpost</groupId>
    <artifactId>client-server-protocol-lib</artifactId>
    <version>0.8</version>
</dependency>
```

Could not find the jar reported in http://mvnrepository.com/artifact/com.sparkpost

**Comment by sks** [comment]
Could not find https://repo.maven.apache.org/maven2/com/sparkpost/client-server-protocol-lib

**Comment by yepher** [comment]
Have a look here

https://repo1.maven.org/maven2/com/sparkpost/sparkpost-lib/0.8/

**Comment by sks** [comment]
Thanks

**Comment by mihaita-tinta** [comment]
The artifactId was changed:
<dependency>
		 <groupId>com.sparkpost</groupId>
		  <artifactId>sparkpost-lib</artifactId>
		  <version>0.10</version>
</dependency>
