### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/java-sparkpost#2]
We need to include continuous integration testing using [Travis CI](https://travis-ci.org/).

- [ ] Integrate with Travis CI
- [ ] Add build status button on README.md file similar to the status on [this page](https://github.com/SparkPost/node-sparkpost) above the logo in the README.md

**Comment by richleland** [comment]
Added badge to readme and travis config. Right now the build fails when running on openjdk 6. I need to know which versions we're going to test and update the travis config accordingly.

Default is:

```
jdk:
  - oraclejdk7
  - openjdk6
```

All available versions per travis are OpenJDK 6, OpenJDK 7, Oracle JDK 7, and Oracle JDK 8.

**Comment by yepher** [comment]
The project requires Java 1.7 or higher so from the choices you listed it would need to be oraclejdk7/
