### ISSUE TITLE
Wrong maven dependency

### ISSUE THREAD

**Issue by witeX** [SparkPost/java-sparkpost#21]
Hi,

In readme defined lib 
<dependency>
    <groupId>com.sparkpost</groupId>
    <artifactId>client-server-protocol-lib</artifactId>
    <version>0.10</version>
</dependency>
need to define 

<dependency>
            <groupId>com.sparkpost</groupId>
            <artifactId>sparkpost-lib</artifactId>
            <version>0.10</version>
        </dependency>

**Comment by yepher** [comment]
Thank your for creating this issue. I will fix this.

**Comment by yepher** [comment]
Fixed in this commit

https://github.com/SparkPost/java-sparkpost/commit/e582aacb1f15d50cfbb20bba5b36ee3b179e5368
