### ISSUE TITLE
Substitution data as string

### ISSUE THREAD

**Issue by jygoubet** [SparkPost/java-sparkpost#24]
Hi,

It looks like substitution data can only be strings key/value pairs but the value should be an array too. 

Am I missing something to do so ?

Thanks

**Comment by yepher** [comment]
You are correct. The java library currently limits substitution data to a single string. I recently started thinking through how to expose the more complex substitution schemes that SparkPost supports.

I would welcome a Pull Requests that addresses this if you are up for it. Otherwise I am going to work on this in the near future.

**Comment by jygoubet** [comment]
Ok thanks I'll have a look one of these days if we decide to use sparkpost and it's still an issue

**Comment by carmudgeon** [comment]
this means i wont be able to do something like this?

` "substitution_data": {
        "subject" : "Inconsistencias",
        "processingdate": "2016-03-22 14:27:02",
        "inconsistencylist": [
            {
                "guide": "234997175",
                "lastchangeupdatestatedate": "2016-02-23 19:00:59",
                "filename": "P_20160322",
                "amount": 116800
            },
            {
                "guide": "234997177",
                "lastchangeupdatestatedate": "2016-02-23 19:01:00",
                "filename": "P_20160322",
                "amount": 116800
            }
        ]
    }`

**Comment by yepher** [comment]
@carmudgeon 

Yes, that is correct. I am working on a new release that will enable your ability to do that as well as inline css.

**Comment by carmudgeon** [comment]
Hi @yepher i have to ask this, do you have an estimated date of release :)

**Comment by yepher** [comment]
I @carmudgeon I'm trying to have it ready by end of day tomorrow.

**Comment by carmudgeon** [comment]
Awesome!!

**Comment by yepher** [comment]
This is now available in the Maven repo.
