### ISSUE TITLE
Send email to predefined recipient list - TransmissionWithRecipientList can not be send

### ISSUE THREAD

**Issue by mkutlev** [SparkPost/java-sparkpost#39]
I want to send transmission using TransmissionWithRecipientList. 
The problem is that ResourceTransmissions.create method accepts only TransmissionWithRecipientArray.
Could you update the method to use TransmissionBase as type of the transmission?

**Comment by yepher** [comment]
@mkutlev Yes I will fix that and will be available in v0.16

**Comment by kalnik-a-a** [comment]
> Could you update the method to use TransmissionBase as type of the transmission?

It is not a good decision. If parameter type will be changed to TransmissionBase all fields in child Classes will become invisible and method will not work properly.

**Comment by yepher** [comment]
Thanks @kalnik-a-a
