### ISSUE TITLE
Automatically set options.sandbox on sparkpostbox.com `Client.sendMessage()` calls

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/java-sparkpost#54]
The transmission endpoint now respects `options.sandbox` when sending from `sparkpostbox.com` so our "easy button" API clients should set the field appropriately when they detect sandbox domain use. The highest profile use of `Client.sendMessage()` is [here](https://developers.sparkpost.com/).

**Comment by cloud-tribal** [comment]
I am getting this error "Sending domain sandbox option mismatch", yet I've configured my SPARKPOST_SANDBOX_DOMAIN and SPARKPOST_SMTP_HOST as per the docs. 

What is the cause of this problem ?

**Comment by yepher** [comment]
@cloud-tribal I am a little confused by your comment. This library uses the SparkPost REST interface and not SMTP. 

Can you tell me a little more about what your are doing? Are you integrating with Maven or are you using this library directly?
