### ISSUE TITLE
Avoid having duplicate slashes

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/java-sparkpost#60]
According to ESCSP-1390, java-sparkpost sometimes request to endpoint with duplicate slashes. While it used to work earlier and broken now which we're fixing it may not work in future (when we move to ALB routing). 

```/api/v1//transmissions```

**Comment by yepher** [comment]
Did you find a case where there is a multiple slashes. There are unit tests for this condition and they are all passing.

Can you share the file and line number where you found this issue or a test case that reproduces it?

**Comment by yepher** [comment]
@rajumsys I think what your are referring to was fixed in https://github.com/SparkPost/java-sparkpost/issues/57

Let me know if there is another problem.

**Comment by yepher** [comment]
This was fixed in issue #57
