### ISSUE TITLE
How to send mails with attachments of images 

### ISSUE THREAD

**Issue by krishnanrao** [SparkPost/java-sparkpost#64]
I am trying to send email with image attachment how can i achieve it in sparkpost

**Comment by yepher** [comment]
To send attachments through SparkPost you use can either compose and send an RFC822 message with attachments encoded. Or you can use the attachment API shown [here](https://developers.sparkpost.com/api/transmissions.html#header-attachment-attributes).

Here are some examples from the Java library sample code:

Here is an example [SendEmailWithFilesSample.java](https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-samples-app/src/main/java/com/sparkpost/samples/SendEmailWithFilesSample.java#L68)

And this is another example using JavaMail to encode the attachment - [App.java](https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-javamail-app/src/main/java/com/sparkpost/sample/App.java#L151)

I will close this issue but feel free to ask if something is not clear.
