### ISSUE TITLE
Changing Email for each recepint 

### ISSUE THREAD

**Issue by polando** [SparkPost/java-sparkpost#68]
Does `substitutionData` changes the data for all the recipients or is there a way to substitute the data according to each recipient.
For example, if I had a `country field` in my Email and I wanted to change it according to each recipient's country, something like this:

`hello, Mr.X from country_filed`

Could I write something like below to substitute that field according to each recipient:
```
 Map<String, Object> substitutionData = new HashMap<String, Object>();
        substitutionData.put("country_filed", recipient.country);
        transmission.setSubstitutionData(substitutionData);
```

is that possible to do it with one transmission or I have to create separate transmissions for each recipient and call `transmission.setSubstitutionData` for each one?

**Comment by yepher** [comment]
You can do it either way.

If you set the substitution data on [RecipientAttributes](https://github.com/SparkPost/java-sparkpost/blsubstitutionDatarkpost-lib/src/main/java/com/sparkpost/model/RecipientAttributes.java) the substitution is per recipient.  I think [SendEmailWithSubstitutionSample.java](https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-samples-app/src/main/java/com/sparkpost/samples/SendEmailWithSubstitutionSample.java#L57) is an example of what you are trying to do.

## You can read more about substitutions:
* https://developers.sparkpost.com/api/substitutions-reference.html
* https://developers.sparkpost.com/api/substitutions-reference.html#header-substitutions-syntax-examples
