### ISSUE TITLE
Android Gradle Release

### ISSUE THREAD

**Issue by geniushkg** [SparkPost/java-sparkpost#69]
Hi team,

I used [`Gradle please`](http://gradleplease.appspot.com/#sparkpost) but that's giving me concurrent exception error while building also , depency is ignored 'org.apache:commons' httpclient

Please provide clear instruction on how to use sparkpost from android.

Thanks and Regards,

**Comment by yepher** [comment]
It has been several years since I worked on Android. As I recall Android provides it own customized version of `'org.apache:commons httpclient `. I've not tested on Android but I believe it should work fine.

As for integration with Gradle, I expected it to work with the provided POM. Can you tell me a little more about the concurrent error you are seeing?

**Comment by geniushkg** [comment]
I managed by making rest request using curl example , It would be great if you build an sdk on top of okhttp. I will try if possible will provide a wrapper class on  top of rest api to send emails for android.

**Comment by yepher** [comment]
Sure, if you would like to update the library to use okHTTP just submit a pull request. 

All the HTTP calls are in com.sparkpost.transport.RestConnection and that implements an Interface. So you could make a second implementation or retrofit the existing class. I expect most of the changes would be in the doHTTP method and the challenging bit (not that challenging) would be the non 2xx error handling.

**Comment by yepher** [comment]
Also for your reference refer to https://github.com/SparkPost/java-sparkpost/blob/master/CONTRIBUTING.md for how to build project and some othe helpful information.

**Comment by yepher** [comment]
You can now provide your own RestConnection class that implements [IRestConnection](https://github.com/SparkPost/java-sparkpost/blob/master/libs/sparkpost-lib/src/main/java/com/sparkpost/transport/IRestConnection.java).

That should resolve this issue.
