### ISSUE TITLE
Ability to set from name

### ISSUE THREAD

**Issue by tobiasjunsten** [SparkPost/java-sparkpost#77]
At the moment I see no possibility to set the from name when sending an email. Only the from address can be set.

**Comment by yepher** [comment]
Have you tried this?

```
AddressAttributes fromAddress = new AddressAttributes("alice@example.com);
fromAddress.setName("Alice Of Wonderland");
contentAttributes.setFrom(fromAddress);
```

[AddressAttribute::name](https://github.com/SparkPost/java-sparkpost/blob/master/libs/sparkpost-lib/src/main/java/com/sparkpost/model/AddressAttributes.java#L40)

You can modify this sample too test that out: [SendEmailSample](https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-samples-app/src/main/java/com/sparkpost/samples/SendEmailSample.java#L68).

I hope that helps. I am going to close this issue. Re-open it if you have any issues with this API.

**Comment by tobiasjunsten** [comment]
Maybe I should have clarified that I meant when using the Client class to avoid writing all that extra code. But don't worry about it I'm not using the library anymore.
