### ISSUE TITLE
Unable to send bulk mail getting undermine type boune

### ISSUE THREAD

**Issue by amitthakur4820** [SparkPost/java-sparkpost#82]
Hi there,
I have build sparkpost interface by using jsp and sevrlets,I can send test mail through it, but when I am trying to send bulk mail  by connecting to my local mysql database then it send only first mail in the list and rest of the are appear as bounced back

While running  still I am using log4j properties file in my webapp
 I got one warning every time by log4j frame still I am using log4j properties file in my webapp

![capture](https://user-images.githubusercontent.com/35639203/36901309-bf4f709a-1e4c-11e8-805f-1f9007c1cc25.PNG)

**Comment by yepher** [comment]
Are you getting any error back from the server?

When you get the bounce what is the message you get?

**Comment by yepher** [comment]
Can you share a sample of your code where you add the recipients?

**Comment by amitthakur4820** [comment]
while(rs.next())
				 
				 
				{
				 
				counter++;
				
			String tmail=rs.getString(2);
	
			
			
			
		
			 Client client = new Client(API_KEY);
			  System.out.print(tmail.trim()+"5");
			


					try {
						//client.sendMessage( "amit <"                           +fmail+">",tmail, subject,"dfghj","<b>fgn</b>");
						client.sendMessage(fmail,tmail.trim(), subject, "thisismytestmail", "");
						System.out.println("mas send succsesfully");
					} catch (SparkPostException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						out.println("error cause"+e);
					}

**Comment by yepher** [comment]
I think you may find this sample helpful for sending a message to multiple recipients:
https://github.com/SparkPost/java-sparkpost/blob/master/apps/sparkpost-samples-app/src/main/java/com/sparkpost/samples/SendEmailSample.java#L53

**Comment by yepher** [comment]
This was a usage issue an not a library issue so closing this ticket.
