### ISSUE TITLE
Webhook properties are out of date

### ISSUE THREAD

**Issue by tommairs** [SparkPost/java-sparkpost#90]
This is not current, please update with an accurate list of properties.
https://github.com/SparkPost/java-sparkpost/blob/master/libs/sparkpost-lib/src/main/java/com/sparkpost/model/webhook/event/DeliveryEvent.java

**Comment by yepher** [comment]
Ran the code to re-generate all the Webhook event classes. These are meant as a reference.
See [here](https://github.com/SparkPost/java-sparkpost/tree/master/libs/sparkpost-lib/src/main/java/com/sparkpost/model/webhook/event)

They will be released in the next version of the library >= 0.24
