### ISSUE TITLE
attach pdf 

### ISSUE THREAD

**Issue by timosalex** [SparkPost/java-sparkpost#91]
Hi I am trying to attach a pdf to an email using your java api.
However it is not clear to me how I can achieve that.  What string should I pass on the .setData() function

```
attachment.setName("name.pdf");
 attachment.setType("pdf;");
 attachment.setData("how do i pass my pdf here?");
				
				
		       
```

Any help?

**Comment by stevebor1** [comment]
The data needs to be Base64 encoded. 

    byte[] bytes = IOUtils.toByteArray(yourinputstream);
    String encoded = Base64.getEncoder().encodeToString(bytes);
    attachment.setData(encoded);

**Comment by yepher** [comment]
See previous comment or samples for how to do this.
